### ISSUE TITLE
マジックナンバーは使わないほうが良いです

### ISSUE THREAD

**Issue by isso0424** [kota-yata/Payrox-cal#3]
こんばんは。茨城高専2年のisso0424です。
Qiitaの記事を見て来ました。
このコードのリファクタリングをしようとしましたが、大規模なモノになってしまいそうでした。
そのため、思ったいくつかのことについてIssueという形で指摘させていただきます。
まず、1つ目なんですがマジックナンバー(ソースコードに直書きする値)は使わないほうが良いです。
これは特別な場合(深夜労働など)にかけられている値になります。
今回の場合はObjectとして`{key: value}`のような値を定義すると良いと思います。

マジックナンバーが嫌われる理由としてはメンテナンス性の低さがあります。
今回の場合、マジックナンバーを使っていると法改正などでコードに変更を加える場合にコード全体から探して書き換える必要があります。
それよりはObjectなどとして持っていたほうがメンテナンス性の高いコードとなるのでマジックナンバーは嫌われやすいです。

**Comment by kota-yata** [comment]
アドバイスありがとうございます。
反論の余地はありませんので修正しました。
ありがとうございました。
