### ISSUE TITLE
コメントアウトは極力減らしましょう

### ISSUE THREAD

**Issue by isso0424** [kota-yata/Payrox-cal#5]
ソースコードを見た限りほぼ1行に1回コメントアウトが行われているような状況に見えました。
これは[リーダブルコード](https://www.amazon.co.jp/リーダブルコード-―より良いコードを書くためのシンプルで実践的なテクニック-Theory-practice-Boswell/dp/4873115655)という書籍に書いてあるのですが、「コードからすぐわかることをコメントに書くべきでない」という一般論があります。

これはコードからわかることで画面を専有すべきでは無いという考え方から来ています。

**Comment by kota-yata** [comment]
アドバイスありがとうございます。
今までは一つ一つマジックナンバーを入力していたため修正の際にすぐにどこを直すべきか判断できるように1行ずつコメントアウトしていましたが、issue #3 のアドバイスを受けてオブジェクトで管理することにしたのでその必要がなくなりました。
#3 と同時にcloseさせていただきます。ありがとうございました。
