### ISSUE TITLE
割増賃金に関する情報源を提示してほしい

### ISSUE THREAD

**Issue by raiga0310** [kota-yata/Payrox-cal#6]
こんにちは。技術的な話ではないのですが、割増賃金について、気になったことを質問させていただきます。
Qiitaの該当記事に記載されていた条件の倍率や、GitHubのソースコードの倍率はどこを情報源としたものかを教えていただきたいです。また、それが正しいのであればその根拠たる解釈を教えていただきたいです。
労働基準法３７条によれば、
> 使用者が、第三十三条又は前条第一項の規定により労働時間を延長し、又は休日に労働させた場合においては、その時間又はその日の労働については、通常の労働時間又は労働日の賃金の計算額の二割五分以上五割以下の範囲内でそれぞれ政令で定める率以上の率で計算した割増賃金を支払わなければならない。ただし、当該延長して労働させた時間が一箇月について六十時間を超えた場合においては、その超えた時間の労働については、通常の労働時間の賃金の計算額の五割以上の率で計算した割増賃金を支払わなければならない。

とあり、具体的な時間外労働や、法定休日に置いての労働時間に対する割増賃金の増加率は政令や企業により任意で決められる、と書いてあるという解釈をしました。
よって倍率は現行のソースコードに記載されている倍率とは違う恐れがあります。
もし倍率が違う企業がこのパッケージを採用した場合、企業にとって多大な計算損失が発生することになるのを危惧しました。
また、倍率が異なる恐れのある、という自分の指摘は、下記のリンクの厚生労働省の就労条件報告に基づくものであります。このように企業により、割増賃金の倍率設定が違う場合がありますので、こういった形での質問をさせていただきました。長文ではありますが、公開されているパッケージということも考慮しております。回答をお待ちしています。
https://www.mhlw.go.jp/toukei/itiran/roudou/jikan/syurou/18/dl/gaiyou02.pdf

**Comment by kota-yata** [comment]
ご質問ありがとうございます。
基本的に、僕は以下の労働基準法第三十七条とPDFを情報源として使用し、この資料に書いてある通りに割増賃金を設定していました。

>使用者が、第三十三条又は前条第一項の規定により労働時間を延長し、又は休日に労働させた場合においては、その時間又はその日の労働については、通常の労働時間又は労働日の賃金の計算額の二割五分以上五割以下の範囲内でそれぞれ政令で定める率以上の率で計算した割増賃金を支払わなければならない。ただし、当該延長して労働させた時間が一箇月について六十時間を超えた場合においては、その超えた時間の労働については、通常の労働時間の賃金の計算額の五割以上の率で計算した割増賃金を支払わなければならない。
○２　前項の政令は、労働者の福祉、時間外又は休日の労働の動向その他の事情を考慮して定めるものとする。
○３　使用者が、当該事業場に、労働者の過半数で組織する労働組合があるときはその労働組合、労働者の過半数で組織する労働組合がないときは労働者の過半数を代表する者との書面による協定により、第一項ただし書の規定により割増賃金を支払うべき労働者に対して、当該割増賃金の支払に代えて、通常の労働時間の賃金が支払われる休暇（第三十九条の規定による有給休暇を除く。）を厚生労働省令で定めるところにより与えることを定めた場合において、当該労働者が当該休暇を取得したときは、当該労働者の同項ただし書に規定する時間を超えた時間の労働のうち当該取得した休暇に対応するものとして厚生労働省令で定める時間の労働については、同項ただし書の規定による割増賃金を支払うことを要しない。
○４　使用者が、午後十時から午前五時まで（厚生労働大臣が必要であると認める場合においては、その定める地域又は期間については午後十一時から午前六時まで）の間において労働させた場合においては、その時間の労働については、通常の労働時間の賃金の計算額の二割五分以上の率で計算した割増賃金を支払わなければならない。
○５　第一項及び前項の割増賃金の基礎となる賃金には、家族手当、通勤手当その他厚生労働省令で定める賃金は算入しない。
（時間計算）

https://jsite.mhlw.go.jp/tokyo-roudoukyoku/content/contents/000501860.pdf

raiga0310さんに提示いただいたデータによると通常の時間外労働に関する割増賃金については、**大半の企業が25%を採用しており、これに関しては変更する必要はない**ものと思われます。
また、月60時間を超える時間外労働に関する割増賃金について、中小企業以外においてはほぼ50%以上で定めており、2023年の法律改正により中小企業含め全ての企業が50%以上に設定することが義務付けられるため、**今後徐々に50%以上に設定する企業が増えると予想**いたしました。そのためこの数値についても変更する必要はないと判断しました。なお、データを見る限り、通常の時間外労働割増賃金を25%の規定最低ラインで定めている企業が多いことから、月60時間超えの割増についても規定最低ラインで定めている企業がほとんどであると予測しております。

勿論、各割増賃金について自由に設定できる引数などを設ける、と言った解決策はありますが、**このパッケージはあくまで従業員側に向けたもの**であり、ほとんどの従業員にとっては現状通りの割増賃金設定で問題ない、オプションを設定するとむしろ使いにくくなると思われます。

もしこれを覆すデータ等が見つかれば、是非もう一度issueを立てていただき、ご質問いただければ幸いです。

Qiitaの記事でこのソースを掲載しなかったことについては申し訳なく思っております。今回は履歴から訪れたデータを探して提示いたしましたが、Qiitaの記事を書く際に、**「履歴辿るのめんどいし労働基準法だけでいっか」**と判断し、大した根拠にならない労働基準法のみを掲載しておりました。今後はしっかり参考資料全てを提示することを約束いたします。

ご質問ありがとうございました。
