### ISSUE TITLE
関数の引数はJSDocに書きましょう

### ISSUE THREAD

**Issue by isso0424** [kota-yata/Payrox-cal#7]
今の状態だと引数がコメントに書かれているだけの状態です。
これに型などの情報を明記し、IDEなどで補完に利用できるようにできます。

それが[JSDoc](https://ics.media/entry/6789/)です。

これを使うことで型ごとの補完をつけられるようになります。
さらに形式を統一することで初めてコードを読んだ人が理解しやすくなるというメリットもあります。

**Comment by kota-yata** [comment]
JSDocコメントアウトを追加しました
